export const Category = {
    BREKKIE: 'BREKKIE',
    SOUP: 'SOUP',
    PASTA: 'PASTA',
    OTHER: 'OTHER',
};

const Recipes = [
    {
        name: 'porridge',
        id: 'porridge',
        category: Category.BREKKIE,
        ingredients: [
            '2/3 cup steel cut oats',
            '2/3 cup unsweetened almond milk',
            '2 tablespoons raw pepitas, roughly chopped',
            'pinch ground ginger',
            'pinch ground cinnamon',
            'pinch ground nutmeg',
            '2 tablespoons hemp seeds',
            '1 tablespoons almond butter',
            '2 teaspoons chia seeds',
            '1/2 teaspoon vanilla extract',
        ],
        instructions: [
            'Bring the oats and 2/3 cup water to a boil in a medium saucepan over medium high heat',
            'Reduce the heat to low and stir in the almond milk, pepitas, ginger, cinnamon, and nutmeg',
            'Cook, stirring occasionally, for about 10 minutes, until the oats are tender',
            'Remove from heat and stir in the hemp seeds, almond butter, chia seeds, and vanilla',
            'Taste, adding your choice of sweetener as desired for a sweeter porridge',
        ],
    },
    {
        name: 'veggie broth',
        id: 'veggie-broth',
        category: Category.SOUP,
        ingredients: [
            '2 large piece dried kombu',
            '1 cup chopped carrots',
            '1 cup chopped celery',
            'couple dried mushrooms',
            '1 inch piece fresh ginger, sliced',
            '2 tablespoons nutritional yeast',
            '2 tablespoons olive oil',
            '3 tablespoons tamari',
            '1/2 teaspoon ground turmeric',
        ],
        instructions: [
            'Place in a large stockpot and simmer on low for at least 2 hours, stirring occasionally',
            'Let cool, then strain through a fine-mesh strainer',
        ],
    },
    {
        name: 'veggie soup',
        id: 'veggie-soup',
        category: Category.SOUP,
        ingredients: [
            '1 teaspoon olive oil',
            '2 carrots, chopped',
            '1 celery stalk, chopped',
            '2 tablespoons fresh green onions, chopped',
            '1/4 teaspoon salt, plus more to taste',
            '1/8 teaspoon freshly ground black pepper, plus more to taste',
            '2 1/2 cups broth',
            '1/3 cup wild rice',
            '1/2 cup chickpeas',
            '1 cup kale, stems removed and roughly chopped',
        ],
        instructions: [
            'In a medium saucepan, heat the olive oil over medium high heat',
            'Add the carrots, celery, green onions, salt, and pepper',
            'Cook for 3 to 5 minutes, until the vegetables are crisp-tender',
            'Add in the broth, rice, and 1/2 cup water',
            'Bring the mixture to a boil, then cover and reduce the heat to low',
            'Simmer for about 40 minutes, until the rice has softened',
            'Mix in the chickpeas and kale and cook until the kale is just wilted, about 5 minutes',
            'Add salt and pepper to taste',
        ],
    },
    {
        name: 'lentil soup',
        id: 'lentil-soup',
        category: Category.SOUP,
        ingredients: [],
        instructions: [],
    },
    {
        name: 'chicken tortilla',
        id: 'chicken-tortilla',
        category: Category.SOUP,
        ingredients: [],
        instructions: [],
    },
    {
        name: 'spinach sausage orzo',
        id: 'spinach-sausage-orzo',
        category: Category.SOUP,
        ingredients: [],
        instructions: [],
    },
    {
        name: 'mushroom risotto',
        id: 'mushroom-risotto',
        category: Category.PASTA,
        ingredients: [
            '4 cups broth',
            '2 tablespoons garlic infused olive oil',
            '8 ounces oyster mushrooms, chopped',
            'salt',
            '1 1/4 cups arborio or other short-grain rice',
            '1 tablespoon freshly squeezed lemon juice',
            '3 tablespoons nutritional yeast',
            'fresh parsley for serving',
        ],
        instructions: [
            'In a small saucepot, heat the broth over medium heat',
            'Once simmering, reduce the heat to low to keep warm',
            'While the broth is heating, heat a separate large saucepan over medium heat',
            'Once hot, add in 1 tablespoon olive oil and heat until just shimmering, then add the mushrooms and a pinch of salt',
            'Saute for about 10 minutes, until tender and browned',
            'Remove from the pan and set aside',
            'Heat the remaining 1 tablespoon of oil in the saucepan and add the rice',
            'Cook, stirring often, for 1 minute until just lightly toasted',
            'Using a ladle, add in the warmed vegetable broth, 1/2 cup at a time, stirring almost constantly, allowing the rice to absorb all of the liquid',
            'Take care not to boil the mixture, as that will result in gummy risotto; the heat should be no higher than medium, with the mixture at a slight simmer',
            'Continue to add in the vegetable broth, 1/2 cup at a time, stirring to incorporate until the liquid is mostly absorbed before adding in more broth. The whole process should take about 20 minutes, until the rice is al dente.',
            'Add the lemon juice, nutritional yeast, and reserved mushroom, stirring to combine',
            'Depending on your broth you likely do not need any more salt, but season to taste as desired. Serve with chopped parsley as desired',
        ],
    },
    {
        name: 'stuffed cabbage rolls',
        id: 'stuffed-cabbage-rolls',
        category: Category.OTHER,
        ingredients: [],
        instructions: [],
    },
];

export default Recipes;
