export const Category = {
    BREAKFAST: 'BREAKFAST',
    SOUP: 'SOUP',
    PASTA: 'PASTA',
    OTHER: 'OTHER',
};

const Recipes = [
    //     {
    //         name: 'porridge',
    //         id: 'porridge',
    //         category: Category.BREAKFAST,
    //         ingredients: [
    //             '⅔ cup steel cut oats',
    //             '⅔ cup unsweetened almond milk',
    //             '2 tablespoons raw pepitas, roughly chopped',
    //             'pinch ground ginger',
    //             'pinch ground nutmeg',
    //             '⅛ tsp ground cinnamon',
    //             '1 tablespoons hemp seeds',
    //             '1 tablespoon chia seeds',
    //             '1 tablespoons almond butter',
    //             '½ teaspoon vanilla extract',
    //         ],
    //         instructions: [
    //             'Bring the oats, a pinch of salt, and 1 cup water to a boil in a medium saucepan over medium high heat',
    //             'Reduce the heat to low and stir in the almond milk, pepitas, ginger, cinnamon, and nutmeg',
    //             'Cook, stirring occasionally, for about 10 minutes, until the oats are tender',
    //             'Remove from heat and stir in the hemp seeds, almond butter, chia seeds, and vanilla',
    //             'Taste, adding your choice of sweetener as desired for a sweeter porridge',
    //         ],
    //     },
    //     {
    //         name: 'veggie broth',
    //         id: 'veggie-broth',
    //         category: Category.SOUP,
    //         ingredients: [
    //             '2 large piece dried kombu',
    //             '1 cup chopped carrots',
    //             '1 cup chopped celery',
    //             'couple dried mushrooms',
    //             '1 inch piece fresh ginger, sliced',
    //             '2 tablespoons nutritional yeast',
    //             '2 tablespoons olive oil',
    //             '3 tablespoons tamari',
    //             '½ teaspoon ground turmeric',
    //         ],
    //         instructions: [
    //             'Place in a large stockpot and simmer on low for at least 2 hours, stirring occasionally',
    //             'Let cool, then strain through a fine-mesh strainer',
    //         ],
    //     },
    //     {
    //         name: 'veggie soup',
    //         id: 'veggie-soup',
    //         category: Category.SOUP,
    //         ingredients: [
    //             '1 teaspoon cooking oil',
    //             '2 carrots, chopped',
    //             '1 celery stalk, chopped',
    //             '2 tablespoons fresh green onions, chopped',
    //             '¼ teaspoon salt, plus more to taste',
    //             '⅛ teaspoon freshly ground black pepper, plus more to taste',
    //             '2 ½ cups broth',
    //             '⅓ cup wild rice',
    //             '½ cup chickpeas',
    //             '1 cup kale, stems removed and roughly chopped',
    //         ],
    //         instructions: [
    //             'In a medium saucepan, heat the oil over medium high heat',
    //             'Add the carrots, celery, green onions, salt, and pepper',
    //             'Cook for 3 to 5 minutes, until the vegetables are crisp-tender',
    //             'Add in the broth, rice, and ½ cup water',
    //             'Bring the mixture to a boil, then cover and reduce the heat to low',
    //             'Simmer for about 40 minutes, until the rice has softened',
    //             'Mix in the chickpeas and kale and cook until the kale is just wilted, about 5 minutes',
    //             'Add salt and pepper to taste',
    //         ],
    //     },
    {
        name: 'lentil soup',
        id: 'lentil-soup',
        category: Category.SOUP,
        ingredients: [
            '1 cup green lentils',
            '1 cup red lentils',
            '1 cup black lentils',
            '2 onions',
            '3 cloves garlic',
            '1 can tomato paste',
            '2 cups broth',
            '½ cup olive oil',
            'Salt and pepper to taste',
        ],
        instructions: [
            'Pressure cook green and red lentils with ?? cups water for ?? minutes',
            'Pressure cook red lentils with ?? cups water for ?? minutes',
            'Pressure cook black lentils with ?? cups water for ?? minutes',
            'Dice onions',
            'Mince garlic',
            'Fry up onions, adding garlic once onions almost done',
            'Add cooked lentils, onions, and garlic to large pot',
            'Add broth and tomato paste',
            'stir to combine',
            'Scoop out about a cup and blend with the olive oil',
            'Add back to pot and let simmer for a bit. can add a bay leaf if you want',
            'add salt and pepper to taste',
        ],
    },
    {
        name: 'chicken tortilla soup',
        id: 'chicken-tortilla-soup',
        category: Category.SOUP,
        ingredients: [
            '2 teaspoons cooking oil',
            '1 cup onion, chopped (about 1 small)',
            '2 cups celery, sliced (about 4 medium stalks)',
            '4 garlic cloves, minced',
            '4 medium tomatoes, chopped (or 2 cans diced tomatoes)',
            '2 cups water',
            '4 cups chicken broth',
            '3 cups shredded rotisserie chicken',
            '2 cups thinly sliced carrots (about 3 medium)',
            '1 teaspoon dried oregano leaves',
            '1 teaspoon chili powder',
            '1 teaspoon garlic powder',
            '1 teaspoon cumin',
            '½ teaspoon cayenne pepper',
            '½ teaspoon salt + more to taste',
            '½ teaspoon pepper + more to taste',
            'optional garnish: chopped avocado, chopped fresh cilantro, crumbled Cotija cheese, Greek yogurt',
        ],
        instructions: [
            'Heat oil in large saucepan over medium-high heat',
            'Add chopped onion and celery; cook, stirring frequently, for about 5 minutes and until veggies are soft',
            'Add garlic; cook, stirring frequently, for about 1 minute',
            'Add tomatoes; cook, stirring frequently, for about 5 minutes and until tomatoes are soft',
            'Set aside',
            'Add onion/tomato mixture with 2 cups water (only if not using canned tomatoes) to high-speed blender or food processor and blend until smooth',
            'Transfer blended mixture back to saucepan and add broth, chicken, carrots and seasonings',
            'Bring to a boil',
            'Reduce heat to medium-low; cook, stirring occasionally, for about 10 to 30 minutes, or until carrots are tender',
            'Top each serving with preferred toppings; such as lime juice, avocado, cilantro, cheese, Greek yogurt',
        ],
    },
    {
        name: 'sausage orzo soup',
        id: 'sausage-orzo-soup',
        category: Category.SOUP,
        ingredients: [
            '500 grams Italian Sausage',
            '1 cup Orzo Pasta',
            '1 tbsp Olive Oil',
            '½ Onion',
            '1 tbsp Garlic',
            '1 28 Oz Crushed Tomato',
            '2 tsp Italian Seasoning',
            '½ tsp red chili Flakes (optional)',
            'salt and pepper to taste',
            '4 cups Chicken Broth',
            '2 cups Spinach (Tightly Packed)',
            '¼ cup Half and Half',
            '½ cup Parmesan Cheese (to serve)',
        ],
        instructions: [
            'Saute onion and garlic until the onion has softened and raw garlic smell is gone',
            'Roughly break sausages to small chunks and add to the pan',
            'Saute for 5-6 minutes until they are browned and aromatic',
            'Deglaze the pot by adding stocks and scarp the bottom of the pan to remove any brown bits',
            'Stir in the tomatoes, Italian seasoning, chilli flakes, salt and pepper',
            'When the stock comes to a boil stir in Orzo Pasta',
            'Cover and let it cook for 8-10 minutes in the medium-low heat until Orzo is almost cooked',
            'Stir frequently to prevent Orzo from getting stuck at the bottom',
            'Stir in Spinach to the pot and let it cook for 2 minutes',
            'Switch off the flame and stir in half and half',
            'Serve with a generous topping of parmesan cheese',
        ],
    },
    {
        name: 'mushroom risotto',
        id: 'mushroom-risotto',
        category: Category.PASTA,
        ingredients: [
            '4 cups broth',
            '2 tablespoons garlic infused olive oil',
            '8 ounces oyster mushrooms, chopped',
            'salt',
            '1 ¼ cups arborio or other short-grain rice',
            '1 tablespoon freshly squeezed lemon juice',
            '3 tablespoons nutritional yeast',
            'fresh parsley for serving',
        ],
        instructions: [
            'In a small saucepot, heat the broth over medium heat',
            'Once simmering, reduce the heat to low to keep warm',
            'While the broth is heating, heat a separate large saucepan over medium heat',
            'Once hot, add in 1 tablespoon olive oil and heat until just shimmering, then add the mushrooms and a pinch of salt',
            'Saute for about 10 minutes, until tender and browned',
            'Remove from the pan and set aside',
            'Heat the remaining 1 tablespoon of oil in the saucepan and add the rice',
            'Cook, stirring often, for 1 minute until just lightly toasted',
            'Using a ladle, add in the warmed vegetable broth, ½ cup at a time, stirring almost constantly, allowing the rice to absorb all of the liquid',
            'Take care not to boil the mixture, as that will result in gummy risotto; the heat should be no higher than medium, with the mixture at a slight simmer',
            'Continue to add in the vegetable broth, ½ cup at a time, stirring to incorporate until the liquid is mostly absorbed before adding in more broth. The whole process should take about 20 minutes, until the rice is al dente.',
            'Add the lemon juice, nutritional yeast, and reserved mushroom, stirring to combine',
            'Depending on your broth you likely do not need any more salt, but season to taste as desired. Serve with chopped parsley as desired',
        ],
    },
    {
        name: 'stuffed cabbage rolls',
        id: 'stuffed-cabbage-rolls',
        category: Category.OTHER,
        ingredients: [
            '1 lb hamburger, raw',
            '1 cup rice, uncooked',
            '⅔ cup carrot, shredded',
            '⅔ cup zucchini, shredded',
            '1 medium onion minced',
            '10 oz can diced tomatoes',
            '1 tsp pepper',
            '2 eggs',
            '2 tsp salt',
            '1 large head of cabbage',
            '4 cup tomato juice (but i usually need way more)',
        ],
        instructions: [
            'Preheat your oven to 325°',
            'In a large bowl, mix the first nine ingredients until well combined',
            'Heat some water on high',
            'Cut the rind out of the head of cabbage and blanch in the hot water to help separate the leaves',
            'Remove the leaves from the water when they are tender enough to roll up without the spine of the leaf breaking',
            'Spoon about ⅓ cup mixture in each leaf and roll up tight',
            'Place all the rolls in large casserole and top with tomato juice',
            'Cover and bake at 325° for 1.5 to 2 hours until the rice and hamburger is cooked through',
        ],
    },
];

export default Recipes;
